// Useful sentences for CVOPT Anglès Oral
//
// ESTE ES EL UNICO ARCHIVO QUE SE EDITA. Una frase por linea en SENTENCES:
//    en:     la frase (obligatorio)
//    lesson: la leccion. Usa la constante de LESSON TITLES (obligatorio)
//    fn:     funcion comunicativa en gerundio. Debe estar en FUNCTIONS (obligatorio)
//    topics: temas de ESA frase. [] = frase transversal: solo sale en All y por funcion
//    block:  desplegable de Notion donde aparece (opcional).
//            La pantalla de ese desplegable es  .../useful-sentences/?block=stars-2
//    mp3:    normalmente NO hace falta. La app busca sola audio/<frase-en-minusculas-con-guiones>.mp3
//            ("That's so you!" -> audio/thats-so-you.mp3). Usa mp3: solo si el archivo se llama de otra forma.
//            Si no hay mp3, lee la voz inglesa del dispositivo; si el dispositivo no tiene voz inglesa, no suena.
//
// Un tema nuevo o una funcion nueva aparecen solos en los filtros al usarlos aqui.

// LESSON TITLES
const STARS = "Written in the Stars: Your Professional Year";

// Orden de los temas en el filtro de arriba
const TOPICS = ["Horoscopes", "Personality traits", "Social media", "Stereotypes", "Teamwork", "Job interviews"];

// Orden de las funciones en el filtro "Useful for..."
const FUNCTIONS = [
  "Talking about your feed",
  "Talking about signs and people",
  "Talking about fake news",
  "Guessing signs",
  "Reacting to a guess",
  "Comparing predictions",
  "Reacting to a prediction",
  "Generalising",
  "Predicting",
  "Selling your team",
  "Talking about being judged",
  "Talking about jokes and stereotypes",
  "Talking about labels",
  "Betting on a sign",
  "Justifying a bet",
  "Talking about the elements",
  "Talking about money and ambition",
  "Asking indirect questions",
  "Selling your skills",
  "Justifying a guess",
  "Giving a hiring decision",
  "Playing the astrologer",
  "Giving advice",
  "Assigning tasks",
  "Negotiating",
  "Giving your opinion",,
  "Asking interview questions",
  "Running the interview",
  "Describing yourself",
  "Talking about habits and situations",
  "Talking about strengths and weaknesses",
  "Buying time",
  "Bending the truth",
  "Revealing your sign",
  "Describing personality"
];

const SENTENCES = [

  // stars-1a
  { en: "It pops up on my feed all the time.", lesson: STARS, fn: "Talking about your feed", topics: ["Social media"], block: "stars-1a" },
  { en: "My algorithm has got me figured out.", lesson: STARS, fn: "Talking about your feed", topics: ["Social media"], block: "stars-1a" },
  { en: "It's a bit creepy, actually.", lesson: STARS, fn: "Talking about your feed", topics: ["Social media"], block: "stars-1a" },
  { en: "I just scroll past it.", lesson: STARS, fn: "Talking about your feed", topics: ["Social media"], block: "stars-1a" },
  { en: "She's a textbook Virgo.", lesson: STARS, fn: "Talking about signs and people", topics: ["Horoscopes", "Personality traits"], block: "stars-1a" },
  { en: "It's not really my thing.", lesson: STARS, fn: "Talking about signs and people", topics: ["Horoscopes", "Personality traits"], block: "stars-1a" },
  { en: "I take it with a pinch of salt.", lesson: STARS, fn: "Talking about signs and people", topics: ["Horoscopes", "Personality traits"], block: "stars-1a" },
  { en: "We're complete opposites, actually.", lesson: STARS, fn: "Talking about signs and people", topics: ["Horoscopes", "Personality traits"], block: "stars-1a" },

  // stars-1b
  { en: "It spread like wildfire.", lesson: STARS, fn: "Talking about fake news", topics: ["Social media"], block: "stars-1b" },
  { en: "A lot of people fell for it.", lesson: STARS, fn: "Talking about fake news", topics: ["Social media"], block: "stars-1b" },
  { en: "You can't believe everything you read online.", lesson: STARS, fn: "Talking about fake news", topics: ["Social media"], block: "stars-1b" },
  { en: "It was debunked pretty quickly.", lesson: STARS, fn: "Talking about fake news", topics: ["Social media"], block: "stars-1b" },

  // stars-2
  { en: "Let me take a wild guess.", lesson: STARS, fn: "Guessing signs", topics: ["Horoscopes", "Personality traits"], block: "stars-2" },
  { en: "I'd say you're a water sign, you seem...", lesson: STARS, fn: "Guessing signs", topics: ["Horoscopes", "Personality traits"], block: "stars-2" },
  { en: "You're such a Taurus!", lesson: STARS, fn: "Guessing signs", topics: ["Horoscopes", "Personality traits"], block: "stars-2" },
  { en: "I'm just saying one, honestly.", lesson: STARS, fn: "Guessing signs", topics: ["Horoscopes", "Personality traits"], block: "stars-2" },
  { en: "I say Leo because it's the only one I know.", lesson: STARS, fn: "Guessing signs", topics: ["Horoscopes", "Personality traits"], block: "stars-2" },
  { en: "Total shot in the dark.", lesson: STARS, fn: "Guessing signs", topics: ["Horoscopes", "Personality traits"], block: "stars-2" },
  { en: "That's so you!", lesson: STARS, fn: "Reacting to a guess", topics: ["Horoscopes", "Personality traits"], block: "stars-2" },
  { en: "I'd never have guessed.", lesson: STARS, fn: "Reacting to a guess", topics: ["Horoscopes", "Personality traits"], block: "stars-2" },
  { en: "You don't seem like a typical...", lesson: STARS, fn: "Reacting to a guess", topics: ["Horoscopes", "Personality traits"], block: "stars-2" },
  { en: "Spot on!", lesson: STARS, fn: "Reacting to a guess", topics: ["Horoscopes", "Personality traits"], block: "stars-2" },
  { en: "Not even close.", lesson: STARS, fn: "Reacting to a guess", topics: ["Horoscopes", "Personality traits"], block: "stars-2" },
  { en: "I have no idea how these things work.", lesson: STARS, fn: "Reacting to a guess", topics: ["Horoscopes", "Personality traits"], block: "stars-2" },

  // stars-3
  { en: "Yours looks more optimistic than mine because...", lesson: STARS, fn: "Comparing predictions", topics: ["Horoscopes"], block: "stars-3" },
  { en: "Mine is spot on about...", lesson: STARS, fn: "Comparing predictions", topics: ["Horoscopes"], block: "stars-3" },
  { en: "Mine has nailed it!", lesson: STARS, fn: "Comparing predictions", topics: ["Horoscopes"], block: "stars-3" },
  { en: "Mine got it completely wrong.", lesson: STARS, fn: "Comparing predictions", topics: ["Horoscopes"], block: "stars-3" },
  { en: "Not a single prediction came true.", lesson: STARS, fn: "Comparing predictions", topics: ["Horoscopes"], block: "stars-3" },
  { en: "That sounds just like me.", lesson: STARS, fn: "Reacting to a prediction", topics: ["Horoscopes", "Personality traits"], block: "stars-3" },
  { en: "That sounds nothing like me.", lesson: STARS, fn: "Reacting to a prediction", topics: ["Horoscopes", "Personality traits"], block: "stars-3" },
  { en: "Mine is way too good to be true.", lesson: STARS, fn: "Reacting to a prediction", topics: ["Horoscopes"], block: "stars-3" },
  { en: "Yours is much more down-to-earth.", lesson: STARS, fn: "Reacting to a prediction", topics: ["Horoscopes"], block: "stars-3" },
  { en: "This is pure fantasy, honestly.", lesson: STARS, fn: "Reacting to a prediction", topics: ["Horoscopes"], block: "stars-3" },

  // stars-4
  { en: "All of us are...", lesson: STARS, fn: "Generalising", topics: [], block: "stars-4" },
  { en: "None of us are...", lesson: STARS, fn: "Generalising", topics: [], block: "stars-4" },
  { en: "The main trend in our group is...", lesson: STARS, fn: "Generalising", topics: [], block: "stars-4" },
  { en: "We've noticed that all our cards...", lesson: STARS, fn: "Generalising", topics: [], block: "stars-4" },
  { en: "We're going to...", lesson: STARS, fn: "Predicting", topics: [], block: "stars-4" },
  { en: "We're likely to...", lesson: STARS, fn: "Predicting", topics: [], block: "stars-4" },
  { en: "We'll probably...", lesson: STARS, fn: "Predicting", topics: [], block: "stars-4" },
  { en: "Our biggest risk is...", lesson: STARS, fn: "Predicting", topics: [], block: "stars-4" },
  { en: "We're the safest bet.", lesson: STARS, fn: "Selling your team", topics: ["Teamwork"], block: "stars-4" },
  { en: "We get things done.", lesson: STARS, fn: "Selling your team", topics: ["Teamwork"], block: "stars-4" },
  { en: "We complement each other perfectly.", lesson: STARS, fn: "Selling your team", topics: ["Teamwork"], block: "stars-4" },
  { en: "While the air signs are busy talking, we'll be...", lesson: STARS, fn: "Selling your team", topics: ["Teamwork"], block: "stars-4" },

  // stars-5a
  { en: "They put me in a box.", lesson: STARS, fn: "Talking about being judged", topics: ["Stereotypes"], block: "stars-5a" },
  { en: "It made my blood boil.", lesson: STARS, fn: "Talking about being judged", topics: ["Stereotypes"], block: "stars-5a" },
  { en: "I had to prove them wrong.", lesson: STARS, fn: "Talking about being judged", topics: ["Stereotypes"], block: "stars-5a" },
  { en: "They didn't give me a chance.", lesson: STARS, fn: "Talking about being judged", topics: ["Stereotypes"], block: "stars-5a" },
  { en: "It really gets on my nerves when people assume...", lesson: STARS, fn: "Talking about being judged", topics: ["Stereotypes"], block: "stars-5a" },

  // stars-5b
  { en: "It's funny until it isn't.", lesson: STARS, fn: "Talking about jokes and stereotypes", topics: ["Stereotypes"], block: "stars-5b" },
  { en: "It's a slippery slope.", lesson: STARS, fn: "Talking about jokes and stereotypes", topics: ["Stereotypes"], block: "stars-5b" },
  { en: "It comes from the same place.", lesson: STARS, fn: "Talking about jokes and stereotypes", topics: ["Stereotypes"], block: "stars-5b" },
  { en: "It's a lazy way of thinking.", lesson: STARS, fn: "Talking about jokes and stereotypes", topics: ["Stereotypes"], block: "stars-5b" },
  { en: "You can't compare the two.", lesson: STARS, fn: "Talking about jokes and stereotypes", topics: ["Stereotypes"], block: "stars-5b" },

  // stars-5c
  { en: "You end up acting the part.", lesson: STARS, fn: "Talking about labels", topics: ["Stereotypes"], block: "stars-5c" },
  { en: "We adapt to fit the expectations.", lesson: STARS, fn: "Talking about labels", topics: ["Stereotypes"], block: "stars-5c" },
  { en: "It's hard to break the pattern.", lesson: STARS, fn: "Talking about labels", topics: ["Stereotypes"], block: "stars-5c" },
  { en: "It's a classic case of self-fulfilling prophecy.", lesson: STARS, fn: "Talking about labels", topics: ["Stereotypes"], block: "stars-5c" },

  // stars-6
  { en: "I'd put my money on...", lesson: STARS, fn: "Betting on a sign", topics: ["Horoscopes"], block: "stars-6" },
  { en: "She strikes me as a...", lesson: STARS, fn: "Betting on a sign", topics: ["Horoscopes"], block: "stars-6" },
  { en: "It's a no-brainer: he's a...", lesson: STARS, fn: "Betting on a sign", topics: ["Horoscopes"], block: "stars-6" },
  { en: "I wouldn't be surprised if she was a...", lesson: STARS, fn: "Betting on a sign", topics: ["Horoscopes"], block: "stars-6" },
  { en: "Capricorns are ambitious, so...", lesson: STARS, fn: "Justifying a bet", topics: ["Horoscopes", "Personality traits"], block: "stars-6" },
  { en: "You don't build a fortune like that unless you're...", lesson: STARS, fn: "Justifying a bet", topics: ["Horoscopes", "Personality traits"], block: "stars-6" },
  { en: "Earth signs play the long game, so...", lesson: STARS, fn: "Justifying a bet", topics: ["Horoscopes", "Personality traits"], block: "stars-6" },
  { en: "Fire signs would burn out in an office.", lesson: STARS, fn: "Talking about the elements", topics: ["Horoscopes", "Personality traits"], block: "stars-6" },
  { en: "Earth signs get things done.", lesson: STARS, fn: "Talking about the elements", topics: ["Horoscopes", "Personality traits"], block: "stars-6" },
  { en: "Air signs talk their way into any job.", lesson: STARS, fn: "Talking about the elements", topics: ["Horoscopes", "Personality traits"], block: "stars-6" },
  { en: "Water signs are the ones you call when you're upset.", lesson: STARS, fn: "Talking about the elements", topics: ["Horoscopes", "Personality traits"], block: "stars-6" },
  { en: "They've got the drive.", lesson: STARS, fn: "Talking about money and ambition", topics: ["Personality traits"], block: "stars-6" },
  { en: "They're money-minded.", lesson: STARS, fn: "Talking about money and ambition", topics: ["Personality traits"], block: "stars-6" },
  { en: "They're too busy dreaming.", lesson: STARS, fn: "Talking about money and ambition", topics: ["Personality traits"], block: "stars-6" },
  { en: "They don't care about material wealth.", lesson: STARS, fn: "Talking about money and ambition", topics: ["Personality traits"], block: "stars-6" },

  // stars-7
  { en: "I was wondering if you could tell me...", lesson: STARS, fn: "Asking indirect questions", topics: ["Job interviews"], block: "stars-7" },
  { en: "How would you describe your approach to...?", lesson: STARS, fn: "Asking indirect questions", topics: ["Job interviews"], block: "stars-7" },
  { en: "Could you give me an example of a time when...?", lesson: STARS, fn: "Asking indirect questions", topics: ["Job interviews"], block: "stars-7" },
  { en: "What would you do if...?", lesson: STARS, fn: "Asking indirect questions", topics: ["Job interviews"], block: "stars-7" },
  { en: "I'm reliable under pressure.", lesson: STARS, fn: "Selling your skills", topics: ["Job interviews", "Personality traits"], block: "stars-7" },
  { en: "I'm very detail-oriented.", lesson: STARS, fn: "Selling your skills", topics: ["Job interviews", "Personality traits"], block: "stars-7" },
  { en: "I'd say I'm a team player.", lesson: STARS, fn: "Selling your skills", topics: ["Job interviews", "Personality traits"], block: "stars-7" },
  { en: "I adapt quickly to new systems.", lesson: STARS, fn: "Selling your skills", topics: ["Job interviews", "Personality traits"], block: "stars-7" },
  { en: "I like to finish what I start.", lesson: STARS, fn: "Selling your skills", topics: ["Job interviews", "Personality traits"], block: "stars-7" },
  { en: "I suspect you might be a... because...", lesson: STARS, fn: "Justifying a guess", topics: ["Horoscopes"], block: "stars-7" },
  { en: "The way you talked about... gave it away.", lesson: STARS, fn: "Justifying a guess", topics: ["Horoscopes"], block: "stars-7" },
  { en: "That is a very Virgo answer.", lesson: STARS, fn: "Justifying a guess", topics: ["Horoscopes"], block: "stars-7" },
  { en: "You said you hate routine, so I'd say...", lesson: STARS, fn: "Justifying a guess", topics: ["Horoscopes"], block: "stars-7" },
  { en: "You'd be a great fit for this role.", lesson: STARS, fn: "Giving a hiring decision", topics: ["Job interviews"], block: "stars-7" },
  { en: "We'll be in touch.", lesson: STARS, fn: "Giving a hiring decision", topics: ["Job interviews"], block: "stars-7" },
  { en: "To be honest, I have some reservations.", lesson: STARS, fn: "Giving a hiring decision", topics: ["Job interviews"], block: "stars-7" },
  { en: "What sold me was...", lesson: STARS, fn: "Giving a hiring decision", topics: ["Job interviews"], block: "stars-7" },

  // stars-hotline
  { en: "I'm sensing a lot of tension around you.", lesson: STARS, fn: "Playing the astrologer", topics: ["Horoscopes"], block: "stars-hotline" },
  { en: "The stars are telling me...", lesson: STARS, fn: "Playing the astrologer", topics: ["Horoscopes"], block: "stars-hotline" },
  { en: "Mercury is not on your side this month.", lesson: STARS, fn: "Playing the astrologer", topics: ["Horoscopes"], block: "stars-hotline" },
  { en: "You'd better...", lesson: STARS, fn: "Giving advice", topics: [], block: "stars-hotline" },
  { en: "If I were in your shoes, I'd...", lesson: STARS, fn: "Giving advice", topics: [], block: "stars-hotline" },
  { en: "It might be worth...", lesson: STARS, fn: "Giving advice", topics: [], block: "stars-hotline" },
  { en: "Whatever you do, don't...", lesson: STARS, fn: "Giving advice", topics: [], block: "stars-hotline" },

  // stars-crisis
  { en: "I'm best suited to handle...", lesson: STARS, fn: "Assigning tasks", topics: ["Teamwork"], block: "stars-crisis" },
  { en: "Why don't you take care of...?", lesson: STARS, fn: "Assigning tasks", topics: ["Teamwork"], block: "stars-crisis" },
  { en: "That plays to your strengths.", lesson: STARS, fn: "Assigning tasks", topics: ["Teamwork"], block: "stars-crisis" },
  { en: "If we do that, we might risk...", lesson: STARS, fn: "Negotiating", topics: ["Teamwork"], block: "stars-crisis" },
  { en: "As long as you cover..., I'll...", lesson: STARS, fn: "Negotiating", topics: ["Teamwork"], block: "stars-crisis" },
  { en: "Hang on, what about the customers?", lesson: STARS, fn: "Negotiating", topics: ["Teamwork"], block: "stars-crisis" },

  // stars-reading
  { en: "I reckon...", lesson: STARS, fn: "Giving your opinion", topics: [], block: "stars-reading" },
  { en: "If you ask me...", lesson: STARS, fn: "Giving your opinion", topics: [], block: "stars-reading" },
  { en: "To be fair...", lesson: STARS, fn: "Giving your opinion", topics: [], block: "stars-reading" },
  { en: "I'm not so sure, because...", lesson: STARS, fn: "Giving your opinion", topics: [], block: "stars-reading" },
  // --- Astro-HR Interview (24/09/2026): preguntas, respuestas y adjetivos ---
  { en: "Tell me a bit about yourself. Give me two adjectives that describe your character.", lesson: STARS, fn: "Asking interview questions", topics: ["Job interviews"], block: "hr-questions" },
  { en: "Waiting for instructions or taking the initiative. Which one is you?", lesson: STARS, fn: "Asking interview questions", topics: ["Job interviews"], block: "hr-questions" },
  { en: "A machine stops at 3 a.m. Your supervisor is not answering. What do you do?", lesson: STARS, fn: "Asking interview questions", topics: ["Job interviews"], block: "hr-questions" },
  { en: "Tell me about a time when you had to decide fast.", lesson: STARS, fn: "Asking interview questions", topics: ["Job interviews"], block: "hr-questions" },
  { en: "Someone tells you to wait. How do you feel?", lesson: STARS, fn: "Asking interview questions", topics: ["Job interviews"], block: "hr-questions" },
  { en: "Routine or change. Which one do you prefer?", lesson: STARS, fn: "Asking interview questions", topics: ["Job interviews"], block: "hr-questions" },
  { en: "Same task, three weeks. How do you feel about that?", lesson: STARS, fn: "Asking interview questions", topics: ["Job interviews"], block: "hr-questions" },
  { en: "Tell me about a job you refused to leave half done.", lesson: STARS, fn: "Asking interview questions", topics: ["Job interviews"], block: "hr-questions" },
  { en: "The plan changes at the last minute. What do you do?", lesson: STARS, fn: "Asking interview questions", topics: ["Job interviews"], block: "hr-questions" },
  { en: "A listener or a talker. Which one are you?", lesson: STARS, fn: "Asking interview questions", topics: ["Job interviews"], block: "hr-questions" },
  { en: "A client and your manager disagree in front of you. What do you do?", lesson: STARS, fn: "Asking interview questions", topics: ["Job interviews"], block: "hr-questions" },
  { en: "Tell me about a time when you changed someone's mind.", lesson: STARS, fn: "Asking interview questions", topics: ["Job interviews"], block: "hr-questions" },
  { en: "A very quiet day, no clients. What do you do?", lesson: STARS, fn: "Asking interview questions", topics: ["Job interviews"], block: "hr-questions" },
  { en: "Tasks or people. What comes first for you?", lesson: STARS, fn: "Asking interview questions", topics: ["Job interviews"], block: "hr-questions" },
  { en: "A customer starts crying on the phone. What do you do?", lesson: STARS, fn: "Asking interview questions", topics: ["Job interviews"], block: "hr-questions" },
  { en: "Tell me about a time when you helped a colleague.", lesson: STARS, fn: "Asking interview questions", topics: ["Job interviews"], block: "hr-questions" },
  { en: "An angry customer is shouting at you. What do you do?", lesson: STARS, fn: "Asking interview questions", topics: ["Job interviews"], block: "hr-questions" },
  { en: "Leading or following. Which one do you prefer?", lesson: STARS, fn: "Asking interview questions", topics: ["Job interviews"], block: "hr-questions" },
  { en: "Your team is tired and behind schedule. What do you do?", lesson: STARS, fn: "Asking interview questions", topics: ["Job interviews"], block: "hr-questions" },
  { en: "Tell me about a time when you spoke in front of a group.", lesson: STARS, fn: "Asking interview questions", topics: ["Job interviews"], block: "hr-questions" },
  { en: "Nobody notices your good work. How do you feel?", lesson: STARS, fn: "Asking interview questions", topics: ["Job interviews"], block: "hr-questions" },
  { en: "The big picture or the details. Which one is you?", lesson: STARS, fn: "Asking interview questions", topics: ["Job interviews"], block: "hr-questions" },
  { en: "A tiny mistake, five minutes before delivery. What do you do?", lesson: STARS, fn: "Asking interview questions", topics: ["Job interviews"], block: "hr-questions" },
  { en: "Describe your work day. How do you organise it?", lesson: STARS, fn: "Asking interview questions", topics: ["Job interviews"], block: "hr-questions" },
  { en: "A colleague is very messy. How do you handle that?", lesson: STARS, fn: "Asking interview questions", topics: ["Job interviews"], block: "hr-questions" },
  { en: "Winning the argument or finding agreement. Which one is you?", lesson: STARS, fn: "Asking interview questions", topics: ["Job interviews"], block: "hr-questions" },
  { en: "Two suppliers, the same price. How do you choose?", lesson: STARS, fn: "Asking interview questions", topics: ["Job interviews"], block: "hr-questions" },
  { en: "Tell me about a time when you resolved a conflict between two people.", lesson: STARS, fn: "Asking interview questions", topics: ["Job interviews"], block: "hr-questions" },
  { en: "Two good options. How do you decide?", lesson: STARS, fn: "Asking interview questions", topics: ["Job interviews"], block: "hr-questions" },
  { en: "An open book or a private person. Which one are you?", lesson: STARS, fn: "Asking interview questions", topics: ["Job interviews"], block: "hr-questions" },
  { en: "A colleague asks you how much the boss earns. What do you say?", lesson: STARS, fn: "Asking interview questions", topics: ["Job interviews"], block: "hr-questions" },
  { en: "Tell me about a time when you kept a secret at work.", lesson: STARS, fn: "Asking interview questions", topics: ["Job interviews"], block: "hr-questions" },
  { en: "Working alone for hours. How do you feel about that?", lesson: STARS, fn: "Asking interview questions", topics: ["Job interviews"], block: "hr-questions" },
  { en: "The office or the road. Which one do you prefer?", lesson: STARS, fn: "Asking interview questions", topics: ["Job interviews"], block: "hr-questions" },
  { en: "A client asks your honest opinion about their warehouse. It is a mess. What do you say?", lesson: STARS, fn: "Asking interview questions", topics: ["Job interviews"], block: "hr-questions" },
  { en: "Tell me about a time when you got bored at work.", lesson: STARS, fn: "Asking interview questions", topics: ["Job interviews"], block: "hr-questions" },
  { en: "Two weeks away from home. How do you handle that?", lesson: STARS, fn: "Asking interview questions", topics: ["Job interviews"], block: "hr-questions" },
  { en: "Day by day or with a plan. How do you live?", lesson: STARS, fn: "Asking interview questions", topics: ["Job interviews"], block: "hr-questions" },
  { en: "Where do you see yourself in five years?", lesson: STARS, fn: "Asking interview questions", topics: ["Job interviews"], block: "hr-questions" },
  { en: "The project needs extra hours for six months. What do you do?", lesson: STARS, fn: "Asking interview questions", topics: ["Job interviews"], block: "hr-questions" },
  { en: "Tell me about a goal that took you more than a year.", lesson: STARS, fn: "Asking interview questions", topics: ["Job interviews"], block: "hr-questions" },
  { en: "Follow the manual or improve it. Which one is you?", lesson: STARS, fn: "Asking interview questions", topics: ["Job interviews"], block: "hr-questions" },
  { en: "Everybody in the team agrees. You do not. What do you do?", lesson: STARS, fn: "Asking interview questions", topics: ["Job interviews"], block: "hr-questions" },
  { en: "Tell me about a problem you solved in an unusual way.", lesson: STARS, fn: "Asking interview questions", topics: ["Job interviews"], block: "hr-questions" },
  { en: "A rule makes no sense. What do you do?", lesson: STARS, fn: "Asking interview questions", topics: ["Job interviews"], block: "hr-questions" },
  { en: "A practical person or a dreamer. Which one are you?", lesson: STARS, fn: "Asking interview questions", topics: ["Job interviews"], block: "hr-questions" },
  { en: "A client cannot explain what they want. What do you do?", lesson: STARS, fn: "Asking interview questions", topics: ["Job interviews"], block: "hr-questions" },
  { en: "Tell me about your last really good idea.", lesson: STARS, fn: "Asking interview questions", topics: ["Job interviews"], block: "hr-questions" },
  { en: "You need inspiration. What do you do?", lesson: STARS, fn: "Asking interview questions", topics: ["Job interviews"], block: "hr-questions" },
  { en: "What is your biggest strength? And a weakness?", lesson: STARS, fn: "Asking interview questions", topics: ["Job interviews"], block: "hr-questions" },
  { en: "Thanks for coming in. Please, have a seat.", lesson: STARS, fn: "Running the interview", topics: ["Job interviews"], block: "hr-questions" },
  { en: "Tell me a bit about yourself.", lesson: STARS, fn: "Running the interview", topics: ["Job interviews"], block: "hr-questions" },
  { en: "I see.", lesson: STARS, fn: "Running the interview", topics: ["Job interviews"], block: "hr-questions" },
  { en: "Interesting.", lesson: STARS, fn: "Running the interview", topics: ["Job interviews"], block: "hr-questions" },
  { en: "Right.", lesson: STARS, fn: "Running the interview", topics: ["Job interviews"], block: "hr-questions" },
  { en: "Go on.", lesson: STARS, fn: "Running the interview", topics: ["Job interviews"], block: "hr-questions" },
  { en: "Let me write that down.", lesson: STARS, fn: "Running the interview", topics: ["Job interviews"], block: "hr-questions" },
  { en: "Could you give me an example?", lesson: STARS, fn: "Running the interview", topics: ["Job interviews"], block: "hr-questions" },
  { en: "And how did that go?", lesson: STARS, fn: "Running the interview", topics: ["Job interviews"], block: "hr-questions" },
  { en: "Why do you think that is?", lesson: STARS, fn: "Running the interview", topics: ["Job interviews"], block: "hr-questions" },
  { en: "What did you learn from it?", lesson: STARS, fn: "Running the interview", topics: ["Job interviews"], block: "hr-questions" },
  { en: "Would you say that is typical of you?", lesson: STARS, fn: "Running the interview", topics: ["Job interviews"], block: "hr-questions" },
  { en: "And what about outside work?", lesson: STARS, fn: "Running the interview", topics: ["Job interviews"], block: "hr-questions" },
  { en: "That is all from me. Do you have any questions?", lesson: STARS, fn: "Running the interview", topics: ["Job interviews"], block: "hr-questions" },
  { en: "You would be a great fit for this role.", lesson: STARS, fn: "Giving a hiring decision", topics: ["Job interviews"], block: "hr-questions" },
  { en: "I would say I am...", lesson: STARS, fn: "Describing yourself", topics: ["Job interviews","Personality traits"], block: "hr-answers" },
  { en: "People tell me I am...", lesson: STARS, fn: "Describing yourself", topics: ["Job interviews","Personality traits"], block: "hr-answers" },
  { en: "I am the kind of person who...", lesson: STARS, fn: "Describing yourself", topics: ["Job interviews","Personality traits"], block: "hr-answers" },
  { en: "I am quite..., but not very...", lesson: STARS, fn: "Describing yourself", topics: ["Job interviews","Personality traits"], block: "hr-answers" },
  { en: "That is not really me, to be honest.", lesson: STARS, fn: "Describing yourself", topics: ["Job interviews","Personality traits"], block: "hr-answers" },
  { en: "When I am in a hurry, I tend to...", lesson: STARS, fn: "Talking about habits and situations", topics: ["Job interviews","Personality traits"], block: "hr-answers" },
  { en: "In a conflict, I usually...", lesson: STARS, fn: "Talking about habits and situations", topics: ["Job interviews","Personality traits"], block: "hr-answers" },
  { en: "On a normal Sunday I...", lesson: STARS, fn: "Talking about habits and situations", topics: ["Job interviews","Personality traits"], block: "hr-answers" },
  { en: "I would probably...", lesson: STARS, fn: "Talking about habits and situations", topics: ["Job interviews","Personality traits"], block: "hr-answers" },
  { en: "Once, at work, I...", lesson: STARS, fn: "Talking about habits and situations", topics: ["Job interviews","Personality traits"], block: "hr-answers" },
  { en: "My biggest strength is...", lesson: STARS, fn: "Talking about strengths and weaknesses", topics: ["Job interviews"], block: "hr-answers" },
  { en: "I am good at...", lesson: STARS, fn: "Talking about strengths and weaknesses", topics: ["Job interviews"], block: "hr-answers" },
  { en: "I am not great at..., but I am working on it.", lesson: STARS, fn: "Talking about strengths and weaknesses", topics: ["Job interviews"], block: "hr-answers" },
  { en: "I can be a bit..., to be honest.", lesson: STARS, fn: "Talking about strengths and weaknesses", topics: ["Job interviews"], block: "hr-answers" },
  { en: "What I have learned is...", lesson: STARS, fn: "Talking about strengths and weaknesses", topics: ["Job interviews"], block: "hr-answers" },
  { en: "That is a good question.", lesson: STARS, fn: "Buying time", topics: ["Job interviews"], block: "hr-answers" },
  { en: "Let me think.", lesson: STARS, fn: "Buying time", topics: ["Job interviews"], block: "hr-answers" },
  { en: "Well, it depends.", lesson: STARS, fn: "Buying time", topics: ["Job interviews"], block: "hr-answers" },
  { en: "Do you mean at work or in general?", lesson: STARS, fn: "Buying time", topics: ["Job interviews"], block: "hr-answers" },
  { en: "I would not say that, exactly.", lesson: STARS, fn: "Bending the truth", topics: ["Job interviews"], block: "hr-answers" },
  { en: "Not really, but...", lesson: STARS, fn: "Bending the truth", topics: ["Job interviews"], block: "hr-answers" },
  { en: "I used to, but I have learned to...", lesson: STARS, fn: "Bending the truth", topics: ["Job interviews"], block: "hr-answers" },
  { en: "Some people see that as..., I see it as...", lesson: STARS, fn: "Bending the truth", topics: ["Job interviews"], block: "hr-answers" },
  { en: "Actually, I am a...", lesson: STARS, fn: "Revealing your sign", topics: ["Job interviews","Horoscopes"], block: "hr-answers" },
  { en: "You got it!", lesson: STARS, fn: "Revealing your sign", topics: ["Job interviews","Horoscopes"], block: "hr-answers" },
  { en: "How did you know?", lesson: STARS, fn: "Revealing your sign", topics: ["Job interviews","Horoscopes"], block: "hr-answers" },
  { en: "I was telling the truth the whole time.", lesson: STARS, fn: "Revealing your sign", topics: ["Job interviews","Horoscopes"], block: "hr-answers" },
  { en: "bold", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "decisive", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "fast", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "full of initiative", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "calm under pressure", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "reliable", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "persistent", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "patient", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "consistent", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "happy with routine", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "communicative", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "quick-thinking", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "flexible", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "persuasive", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "able to see both sides", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "caring", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "empathetic", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "people-focused", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "loyal", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "confident", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "motivating", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "a natural presenter", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "responsible", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "visible", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "organised", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "meticulous", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "detail-oriented", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "methodical", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "critical", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "diplomatic", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "fair", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "balanced", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "tactful", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "good at compromise", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "discreet", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "focused", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "trustworthy", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "intense", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "adventurous", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "honest", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "independent", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "adaptable", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "allergic to routine", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "ambitious", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "disciplined", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "a long-term thinker", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "original", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "curious", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "unconventional", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "not afraid of a strange idea", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "creative", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "intuitive", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "imaginative", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "sensitive", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "a visual thinker", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "calm", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "a bit slow to start", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "restless", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "talkative", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "quick", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "private", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "energetic", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "proud", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "kind", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "a bit disorganised", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "direct", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "impatient", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "precise", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "quiet", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "home-loving", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "serious", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "polite", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "indecisive", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "a bit strange", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "slow to react", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "stubborn", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "bored easily", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "impatient with routine", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "easily distracted", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "talks too much", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "too reserved", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "holds grudges", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "needs attention", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "bossy", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "disorganised", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "too sensitive", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "full of energy", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "argumentative", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "too critical", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "worries a lot", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "homesick", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "moody", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "hard-working", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "workaholic", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "cold", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "follows the group", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "rebellious", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  { en: "detached", lesson: STARS, fn: "Describing personality", topics: ["Personality traits","Job interviews"], block: "hr-traits" },
  // --- fin Astro-HR Interview ---
];
